[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>=61", "wheel", "packaging", "tomli;python_version<'3.11'", "versioneer[toml]"]

build-backend = "setuptools.build_meta"

[project]
name = "ibex"
authors = [
  {name = "IBEX Developers"},
  {name = "Olivier Hoenen", email = "olivier.hoenen@iter.org"}
]
description = "Data visualization for IMAS IDS data"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.7"
license-files = ["LICENSE.txt"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Framework :: FastAPI",
    "Framework :: Pytest",
    "Framework :: Sphinx",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: System Administrators",
    "Natural Language :: English",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)"
]
dynamic = ["version"]
dependencies = [
    "imas-python",
    "imas-idstools",
    "uvicorn",
    "fastapi[standard]==0.115.14",
    "packaging",
    "tsdownsample",
    "orjson",
    "autodoc_pydantic",
]

[project.optional-dependencies]
# these self-dependencies are available since pip 21.2
all = [
    "ibex[test]",
    "ibex[linting]",
    "ibex[docs]",
]

test = [
    "pytest",
]

linting = [
    "ruff",
]

docs =[
    "sphinx",
    "sphinx-autosummary-accessors",
    "sphinx_immaterial",
]

benchmark = [
    "asv==0.6.4",
]

[project.urls]
homepage = "https://github.com/iterorganization/IBEX"

[tool.setuptools.packages.find]
where = ["."]
include = ["ibex*"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--strict-markers"
testpaths = "tests"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "ibex/_version.py"
versionfile_build = "ibex/_version.py"
tag_prefix = ""
parentdir_prefix = ""

[tool.ruff]
# Set the maximum line length to 120.
line-length = 120
exclude = ["venv", "_version.py", "versioneer.py"]

[tool.coverage.run]
omit = [
    "ibex/_version.py",
    ]
